apiVersion: batch/v1
kind: Job
metadata:
  name: upgrade
spec:
  template:
    metadata:
      name: upgrade
    spec:
      restartPolicy: OnFailure
      containers:
        - name: upgrade
          image: quay.io/gravitational/debian-tall:buster
          command:
            - /usr/local/bin/helm
            - upgrade
            - --set
            - echoserverRegistry=leader.telekube.local:5000
            - echoserver
            - /var/lib/gravity/resources/charts/echoserver
            - --namespace
            - default
