apiVersion: v1
kind: Service
metadata:
  name: ntp
  namespace: kube-system
  labels:
    app: ntp
spec:
  type: ClusterIP
  selector:
    app: ntp
    role: server
  ports:
    - name: ntp
      port: 123
      protocol: UDP
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: ntp-server
  namespace: kube-system
  labels:
    app: ntp
spec:
  replicas: 1
  selector:
    app: ntp
    role: server
  template:
    metadata:
      labels:
        app: ntp
        role: server
    spec:
      containers:
        - name: ntp
          image: ntp:1.0.0
          command: ["/usr/sbin/ntpd", "-n", "-c", "/etc/ntp/server.conf"]
          ports:
            - name: ntp
              containerPort: 123
              protocol: UDP
          securityContext:
            privileged: true
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: ntp
  namespace: kube-system
  labels:
    app: ntp
spec:
  selector:
    matchLabels:
      app: ntp
      role: client
  template:
    metadata:
      labels:
        app: ntp
        role: client
    spec:
      containers:
        - name: ntp
          image: ntp:1.0.0
          command: ["/bin/sh", "/root/start-client.sh"]
          securityContext:
            privileged: true
