blank_issues_enabled: false
contact_links:
  - name: Gravity Documentation
    url: https://gravitational.com/gravity/docs/
    about: Check out the Gravity documentation for answers to common questions
