apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: imagesets.lens.gravitational.io
spec:
  group: lens.gravitational.io
  version: v2
  scope: Cluster
  names:
    kind: ImageSet
    plural: imagesets
    singular: imageset
    shortNames:
    - imgset
  validation:
    openAPIV3Schema:
      type: object
      required: ["spec"]
      properties:
        spec:
          type: object
          required: ["images"]
          properties:
            images:
              type: array
              items:
                type: object
                required: ["image"]
                properties:
                  image:
                    type: string
                  registry:
                    type: string
