apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "tensorflow-resnet.fullname" . }}
  namespace: {{.Values.tensorNamespace}}
  labels: {{- include "tensorflow-resnet.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels: {{- include "tensorflow-resnet.matchLabels" . | nindent 6 }}
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels: {{- include "tensorflow-resnet.labels" . | nindent 8 }}
      {{- if or .Values.podAnnotations (and .Values.metrics.enabled .Values.metrics.podAnnotations) }}
      annotations:
        {{- if .Values.podAnnotations }}
        {{- include "tensorflow-resnet.tplValue" ( dict "value" .Values.podAnnotations "context" $) | nindent 8 }}
        {{- end }}
        {{- if and .Values.metrics.enabled .Values.metrics.podAnnotations }}
        {{- include "tensorflow-resnet.tplValue" ( dict "value" .Values.metrics.podAnnotations "context" $) | nindent 8 }}
        {{- end }}
      {{- end }}
    spec:
{{- include "tensorflow-resnet.imagePullSecrets" . | indent 6 }}
      {{- if .Values.affinity }}
      affinity: {{- include "tensorflow-resnet.tplValue" (dict "value" .Values.affinity "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.nodeSelector }}
      nodeSelector: {{- include "tensorflow-resnet.tplValue" (dict "value" .Values.nodeSelector "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations: {{- include "tensorflow-resnet.tplValue" (dict "value" .Values.tolerations "context" $) | nindent 8 }}
      {{- end }}
      initContainers:
        - name: seed
          image: {{.Values.client.image.registry}}/{{.Values.client.image.repository}}:{{.Values.client.image.tag}}
          command:
            - "/bin/sh"
            - "-c"
            - |
              if [ -f /seed/.initialized ]; then
                echo "Already initialized. Skipping"
              else
                curl -o {{.Values.model.localFile}} {{.Values.model.modelUrl}}
                cd /seed/ && tar -xzf {{.Values.model.localFile}}  --strip-components=2
                rm {{.Values.model.localFile}} 
                touch /seed/.initialized
              fi
          volumeMounts:
            - name: seed
              mountPath: /seed
      containers:
        - name: tensorflow-serving
          image: {{.Values.server.image.registry}}/{{.Values.server.image.repository}}:{{.Values.server.image.tag}}
#         imagePullPolicy: {{ .Values.server.image.pullPolicy | quote }}
          ports:
            - name: tf-serving
              containerPort: {{ .Values.containerPorts.server }}
            - name: tf-serving-api
              containerPort: {{ .Values.containerPorts.restApi }}
          {{- if .Values.livenessProbe.enabled }}
          livenessProbe:
            tcpSocket:
              port: tf-serving
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.livenessProbe.successThreshold }}
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
          {{- end }}
          {{- if .Values.readinessProbe.enabled }}
          readinessProbe:
            tcpSocket:
              port: tf-serving
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.readinessProbe.successThreshold }}
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
          {{- end }}
          env:
            - name: TENSORFLOW_SERVING_MODEL_NAME
              value: "resnet"
            - name: TENSORFLOW_SERVING_PORT_NUMBER
              value: "{{ .Values.server.port }}"
            - name: TENSORFLOW_SERVING_REST_API_PORT_NUMBER
              value: "{{ .Values.server.restApiPort }}"
            - name: TENSORFLOW_SERVING_ENABLE_MONITORING
              value: {{ ternary "yes" "no" .Values.metrics.enabled | quote }}
          {{- if .Values.resources }}
          resources: {{- toYaml .Values.resources | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: seed
              mountPath: "/bitnami/model-data"
      volumes:
        - name: seed
          emptyDir: {}
