apiVersion: batch/v1
kind: Job
metadata:
  name: echoserver-status
  namespace: default
spec:
  template:
    metadata:
      name: echoserver-status
    spec:
      restartPolicy: OnFailure
      containers:
        - name: echoserver-status
          image: quay.io/gravitational/debian-tall:buster
          command:
            - /bin/sh
            - -c
            - /bin/wget --no-verbose --output-document=- echoserver:$ECHOSERVER_SERVICE_PORT
