apiVersion: batch/v1
kind: Job
metadata:
  name: tele-app-preupdate
spec:
  template:
    metadata:
      name: tele-app-preupdate
    spec:
      restartPolicy: OnFailure
      containers:
      - name: hook
        image: quay.io/gravitational/debian-tall:0.0.1
        command: ["/usr/local/bin/kubectl", "apply", "-f", "/var/lib/gravity/resources/wormhole.yaml"]