#
# looper pod
#
apiVersion: v1
kind: Pod
metadata:
  name: looper
spec:
  volumes:
      - name: bin
        hostPath: 
            path: "/bin"
      - name: usr
        hostPath: 
            path: "/usr"
      - name: lib
        hostPath: 
            path: "/lib"
      - name: lib64
        hostPath:
            path: "/lib64"
  containers:
      - name: looper
        image: looper:1.0.0
        imagePullPolicy: Always
        volumeMounts:
        - mountPath: /bin
          name: bin
          readOnly: true
        - mountPath: /usr
          name: usr
          readOnly: true
        - mountPath: /lib
          name: lib
          readOnly: true
        - mountPath: /lib64
          name: lib64
          readOnly: true
---
#
# webhead pod
#
apiVersion: v1
kind: Pod
metadata:
  name: webhead
  labels:
      name: webhead
spec:
  volumes:
      - name: bin
        hostPath: 
            path: "/bin"
      - name: usr
        hostPath: 
            path: "/usr"
      - name: lib
        hostPath: 
            path: "/lib"
      - name: lib64
        hostPath:
            path: "/lib64"
  containers:
      - name: webhead
        image: webhead:1.0.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          protocol: TCP
        volumeMounts:
        - mountPath: /bin
          name: bin
          readOnly: true
        - mountPath: /usr
          name: usr
          readOnly: true
        - mountPath: /lib
          name: lib
          readOnly: true
        - mountPath: /lib64
          name: lib64
          readOnly: true
---
#
# webhead service
#
apiVersion: v1
kind: Service
metadata:
    name: gravityapp
spec:
    type: LoadBalancer
    ports: 
        - name: http
          port: 80
          protocol: TCP
          targetPort: 8080
    selector:
        name: webhead
